# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 05:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('long', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('firm', models.CharField(max_length=125)),
                ('ammount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('execution', models.FloatField()),
                ('budgetExec', models.FloatField()),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoproyecto.Municipality')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=15)),
                ('vote_date', models.DateTimeField(verbose_name='date voted')),
            ],
        ),
        migrations.CreateModel(
            name='RateItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=75)),
            ],
        ),
        migrations.AddField(
            model_name='rate',
            name='rate_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='geoproyecto.RateItem'),
        ),
        migrations.AddField(
            model_name='project',
            name='rates',
            field=models.ManyToManyField(to='geoproyecto.Rate'),
        ),
    ]
