# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-07 18:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoproyecto', '0003_auto_20180207_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('APOT', 'Agua Potable'), ('ALC', 'Alcantarillado'), ('DEP', 'Deporte'), ('EDU', 'Educación'), ('IVIAL', 'Infraestructura vial'), ('SAL', 'Salud')], default='APOT', max_length=5),
        ),
    ]
