# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-19 12:13
from __future__ import unicode_literals

import datetime
import django.core.validators
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geoproyecto', '0004_project_project_type'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='municipality',
            options={'verbose_name': 'Municipalidad', 'verbose_name_plural': 'Municipalidades'},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'verbose_name': 'Proyecto', 'verbose_name_plural': 'Proyectos'},
        ),
        migrations.RemoveField(
            model_name='rate',
            name='vote_date',
        ),
        migrations.AddField(
            model_name='project',
            name='pic',
            field=models.ImageField(null=True, upload_to='projects'),
        ),
        migrations.AddField(
            model_name='rate',
            name='date voted',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 19, 12, 13, 40, 995720, tzinfo=utc), verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='municipality',
            name='zoom',
            field=models.PositiveSmallIntegerField(verbose_name='Zoom'),
        ),
        migrations.AlterField(
            model_name='project',
            name='ammount',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='project',
            name='budgetExec',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de ejecucion presupuestaria'),
        ),
        migrations.AlterField(
            model_name='project',
            name='execution',
            field=models.FloatField(validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Porcentaje de avance'),
        ),
        migrations.AlterField(
            model_name='project',
            name='firm',
            field=models.CharField(max_length=125, verbose_name='Empresa'),
        ),
        migrations.AlterField(
            model_name='project',
            name='lat',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Latitud'),
        ),
        migrations.AlterField(
            model_name='project',
            name='long',
            field=models.DecimalField(decimal_places=6, max_digits=9, verbose_name='Longitud'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=250, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_type',
            field=models.CharField(choices=[('APOT', 'Agua Potable'), ('ALC', 'Alcantarillado'), ('DEP', 'Deporte'), ('EDU', 'Educación'), ('IVIAL', 'Infraestructura vial'), ('SAL', 'Salud')], default='APOT', max_length=5, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='ip',
            field=models.CharField(max_length=15, verbose_name='IP'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(3), django.core.validators.MinValueValidator(1)], verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='rateitem',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Nombre'),
        ),
    ]
