# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 06:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('geoproyecto', '0005_auto_20180219_0613'),
    ]

    operations = [
        migrations.AddField(
            model_name='municipality',
            name='desc',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='date voted',
            field=models.DateTimeField(default=datetime.datetime(2018, 2, 20, 6, 13, 5, 20569, tzinfo=utc), verbose_name='Fecha'),
        ),
    ]
