# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 06:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('geoproyecto', '0007_auto_20180220_0014'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='date voted',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha'),
        ),
    ]
