# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-20 09:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geoproyecto', '0008_auto_20180220_0015'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='desc',
            field=models.TextField(null=True, verbose_name='Descripción'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pic',
            field=models.ImageField(null=True, upload_to='projects', verbose_name='Fotografia'),
        ),
    ]
