# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-02-21 19:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoproyecto', '0009_auto_20180220_0324'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rate',
            old_name='date voted',
            new_name='vote_date',
        ),
    ]
